source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.0"

gem "bootsnap", ">= 1.4.4", require: false
gem "graphql", "~> 2.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.0"
gem "rack-cors"
gem "rails", "~> 8.0.0"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "factory_bot_rails"
  gem "rspec-rails", "~> 6.0"
end

group :test do
  gem "shoulda-matchers"
end

group :development do
  gem "graphiql-rails"
  gem "graphql-rails-generators"
  gem "listen"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end
