# Add your own tasks in files placed in lib/tasks ending in .rake.
# For example:

# lib/tasks/capistrano.rake
# namespace :deploy do
#   # ...
# end

# Load Rails rakefile extensions
require_relative "config/application"
Rails.application.load_tasks
